# Za okolje lahko uporabimo poljuben Docker, ki je na voljo na
# Docker Hub <https://hub.docker.com/>
image: node:6.9.4

# Za posredovanje produkcijske različice aplikacije na Heroku
# moramo izvesti celostno kloniranje
clone:
  depth:
    full

pipelines:
  branches:
    # Ko posredujemo uveljavitev na vejo razvoja `master` se
    # izvede neprekinjena integracija (CI), ki izvede vse teste
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm test
  custom:
    # Ročna zahteva za izvedbo postavitve, ki izvede vse teste
    # in posreduje aplikacijo na Heroku
    rocna-postavitev:
      - step:
          caches:
            - node
          script:
            - npm install
            - npm test